SIGNATURES = {
    "secrets": [
        dict(name="AWS Access Key",            pattern=r'AKIA[0-9A-Z]{16}',                                                                        severity="critical", context="aws"),
        dict(name="AWS Secret Key",            pattern=r'(?i)aws.{0,20}secret.{0,20}["\'][A-Za-z0-9/+=]{40}["\']',                                 severity="critical", context="aws"),
        dict(name="Google API Key",            pattern=r'AIza[0-9A-Za-z\-_]{35}',                                                                  severity="high",     context="gcp"),
        dict(name="Firebase apiKey",           pattern=r'AIza[0-9A-Za-z\-_]{35}',                                                                  severity="high",     context="firebase"),
        dict(name="Firebase projectId",        pattern=r'"projectId"\s*:\s*"[a-z0-9\-]+"',                                                         severity="low",      context="firebase"),
        dict(name="Stripe Secret Key",         pattern=r'sk_live_[0-9a-zA-Z]{24,}',                                                                severity="critical", context="payment"),
        dict(name="Stripe Test Secret",        pattern=r'sk_test_[0-9a-zA-Z]{24,}',                                                                severity="medium",   context="payment"),
        dict(name="Stripe Publishable Key",    pattern=r'pk_live_[0-9a-zA-Z]{24,}',                                                                severity="medium",   context="payment"),
        dict(name="JWT Token",                 pattern=r'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}',                          severity="high",     context="auth"),
        dict(name="Bearer Token hardcoded",    pattern=r'["\x60]Bearer\s+[A-Za-z0-9\-_=+/]{20,}["\x60]',                                          severity="high",     context="auth"),
        dict(name="GitHub PAT",                pattern=r'ghp_[A-Za-z0-9]{36}',                                                                     severity="critical", context="vcs"),
        dict(name="GitHub Fine-Grained Token", pattern=r'github_pat_[A-Za-z0-9_]{82}',                                                             severity="critical", context="vcs"),
        dict(name="Slack Bot Token",           pattern=r'xox[baprs]-[A-Za-z0-9\-]{10,}',                                                           severity="high",     context="slack"),
        dict(name="Slack Webhook",             pattern=r'hooks\.slack\.com/services/[A-Za-z0-9/]+',                                                severity="high",     context="slack"),
        dict(name="Twilio Account SID",        pattern=r'AC[0-9a-fA-F]{32}',                                                                       severity="high",     context="twilio"),
        dict(name="Twilio Auth Token",         pattern=r'(?i)twilio.{0,20}["\'][0-9a-fA-F]{32}["\']',                                              severity="critical", context="twilio"),
        dict(name="SendGrid API Key",          pattern=r'SG\.[A-Za-z0-9\-_]{22,}\.[A-Za-z0-9\-_]{43}',                                            severity="high",     context="email"),
        dict(name="Mailchimp API Key",         pattern=r'[0-9a-f]{32}-us[0-9]{1,2}',                                                               severity="medium",   context="email"),
        dict(name="Private Key PEM",           pattern=r'-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----',                                     severity="critical", context="crypto"),
        dict(name="Hardcoded Password",        pattern=r'(?i)(password|passwd|pwd)\s*[=:]\s*["\'][^"\']{6,}["\']',                                 severity="high",     context="credentials"),
        dict(name="Basic Auth in URL",         pattern=r'https?://[A-Za-z0-9_\-]+:[A-Za-z0-9_\-]+@',                                               severity="critical", context="credentials"),
        dict(name="Azure Storage Conn String", pattern=r'DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{88}',          severity="critical", context="azure"),
        dict(name="Azure SAS Token",           pattern=r'sig=[A-Za-z0-9%+/=]{43,}',                                                                severity="high",     context="azure"),
        dict(name="GCP Service Account JSON",  pattern=r'"type"\s*:\s*"service_account"',                                                          severity="critical", context="gcp"),
        dict(name="Mapbox Token",              pattern=r'pk\.[A-Za-z0-9\-_]{60,}',                                                                 severity="medium",   context="maps"),
        dict(name="Algolia API Key",           pattern=r'(?i)algolia.{0,30}["\'][A-Za-z0-9]{32}["\']',                                             severity="medium",   context="search"),
        dict(name="HubSpot API Key",           pattern=r'(?i)hubspot.{0,20}["\'][A-Za-z0-9\-]{36}["\']',                                           severity="high",     context="crm"),
        dict(name="Supabase Service Role Key", pattern=r'eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+',                                      severity="high",     context="supabase"),
        dict(name="Supabase URL",              pattern=r'https://[a-zA-Z0-9]+\.supabase\.co',                                                      severity="medium",   context="supabase"),
        dict(name="Sentry DSN",                pattern=r'https://[0-9a-f]{32}@[a-z0-9.]+/[0-9]+',                                                  severity="medium",   context="monitoring"),
        dict(name="NPM Token",                 pattern=r'npm_[A-Za-z0-9]{36}',                                                                     severity="high",     context="vcs"),
        dict(name="Cloudinary URL",            pattern=r'cloudinary://[0-9]+:[A-Za-z0-9_\-]+@',                                                    severity="high",     context="cloud_storage"),
    ],
    "endpoints": [
        dict(name="GraphQL Endpoint",          pattern=r'(?i)["\x60](/graphql|/gql|/api/graphql|/query)["\x60 /]',                                 severity="high",     context="graphql"),
        dict(name="REST API Path",             pattern=r'(?i)["\x60]/api/v[0-9]+/[a-zA-Z0-9/_\-]+',                                                severity="medium",   context="api"),
        dict(name="Admin Panel Path",          pattern=r'(?i)["\x60](/admin|/dashboard|/management|/console|/control[-_]panel|/backstage|/superuser|/ops)["\x60/]', severity="high", context="admin"),
        dict(name="WebSocket URL",             pattern=r'wss?://[a-zA-Z0-9\-_.]+[^\s"\x60]+',                                                      severity="medium",   context="websocket"),
        dict(name="S3 Bucket URL",             pattern=r'(?i)(s3[.\-][a-zA-Z0-9\-]+\.amazonaws\.com|[a-zA-Z0-9\-]+\.s3\.amazonaws\.com)',          severity="high",     context="cloud_storage"),
        dict(name="Internal/Dev Subdomain",    pattern=r'(?i)https?://(internal|dev|staging|preprod|uat|test|qa|sandbox|local)\.[a-zA-Z0-9\-_.]+', severity="high",     context="internal"),
        dict(name="SSRF-prone parameter",      pattern=r'(?i)[?&](url|redirect|next|return|dest|destination|uri|endpoint|path|host|target|proxy)=', severity="high",    context="ssrf"),
        dict(name="Open Redirect Sink",        pattern=r'(?i)(window\.location|location\.href|location\.replace|location\.assign)\s*=\s*[^;]*\+',  severity="medium",   context="open_redirect"),
        dict(name="Fetch with dynamic URL",    pattern=r'fetch\s*\(\s*(params|query|req|request|input|url|href)',                                   severity="medium",   context="ssrf"),
        dict(name="Debug/Health Endpoint",     pattern=r'(?i)["\x60](/debug|/trace|/actuator|/metrics|/health|/env|/__debug__|/phpinfo)["\x60]',   severity="high",     context="debug_endpoint"),
        dict(name="Swagger/OpenAPI UI",        pattern=r'(?i)["\x60](/swagger[-_]?ui|/api[-_]?docs|/openapi|/redoc)["\x60]',                       severity="medium",   context="api_docs"),
        dict(name="Internal IP Address",       pattern=r'(?i)["\x60]https?://(10\.\d+\.\d+\.\d+|172\.(1[6-9]|2[0-9]|3[01])\.\d+\.\d+|192\.168\.\d+\.\d+)', severity="high", context="internal"),
    ],
    "sinks": [
        dict(name="eval()",                    pattern=r'\beval\s*\(',                                                                              severity="high",     context="xss"),
        dict(name="innerHTML assignment",      pattern=r'\.innerHTML\s*=',                                                                          severity="medium",   context="xss"),
        dict(name="outerHTML assignment",      pattern=r'\.outerHTML\s*=',                                                                          severity="medium",   context="xss"),
        dict(name="document.write()",          pattern=r'document\.write\s*\(',                                                                     severity="medium",   context="xss"),
        dict(name="insertAdjacentHTML",        pattern=r'\.insertAdjacentHTML\s*\(',                                                                severity="medium",   context="xss"),
        dict(name="dangerouslySetInnerHTML",   pattern=r'dangerouslySetInnerHTML\s*=\s*\{',                                                         severity="high",     context="xss"),
        dict(name="v-html Vue",                pattern=r'v-html\s*=',                                                                               severity="high",     context="xss"),
        dict(name="setTimeout with string",    pattern=r'setTimeout\s*\(\s*["\x60]',                                                                severity="high",     context="xss"),
        dict(name="setInterval with string",   pattern=r'setInterval\s*\(\s*["\x60]',                                                               severity="high",     context="xss"),
        dict(name="new Function()",            pattern=r'new\s+Function\s*\(',                                                                      severity="high",     context="xss"),
        dict(name="Prototype Pollution",       pattern=r'Object\.assign\s*\(\s*[^,]+,\s*[^)]*(?:req|user|body|params|query|input)',                severity="high",     context="prototype_pollution"),
        dict(name="postMessage listener",      pattern=r'addEventListener\s*\(\s*["\x60]message["\x60]',                                            severity="medium",   context="postmessage"),
    ],
    "debug": [
        dict(name="Debug Flag Enabled",        pattern=r'(?i)(debug|verbose|isDev|isDebug|DEV_MODE)\s*[=:]\s*true',                                 severity="low",      context="debug"),
        dict(name="Source Map Reference",      pattern=r'//[#@]\s*sourceMappingURL=(?!data:)',                                                      severity="medium",   context="source_map"),
        dict(name="TODO/FIXME near auth",      pattern=r'(?i)//\s*(todo|fixme|hack|xxx).{0,80}(auth|secret|token|password|key|admin|vuln|bypass)', severity="medium",   context="comment"),
        dict(name="Sensitive console.log",     pattern=r'(?i)console\.(log|debug|info|warn)\s*\([^)]*?(token|key|secret|password|auth|jwt|bearer)', severity="medium",   context="debug"),
        dict(name="process.env exposure",      pattern=r'process\.env\.[A-Z][A-Z0-9_]{4,}',                                                        severity="medium",   context="env_var"),
        dict(name="Hardcoded localhost",       pattern=r'(?i)["\x60](https?://)?(localhost|127\.0\.0\.1)(:\d+)?[/"\x60]',                          severity="low",      context="debug"),
        dict(name="Disabled SSL verification", pattern=r'(?i)(rejectUnauthorized|verify)\s*[=:]\s*false',                                          severity="high",     context="ssl"),
    ],
}
